import argparse
from pathlib import Path
import whisper
import os
import sys

from src.soap_generator import call_soap_llm

# Load Whisper model once
WHISPER_MODEL = whisper.load_model("base")

def transcribe_audio(audio_path: Path) -> str:
    print(f"[Transcribing] {audio_path}")
    try:
        result = WHISPER_MODEL.transcribe(str(audio_path))
        return result.get("text", "").strip()
    except Exception as e:
        print(f"[ERROR] Failed to transcribe {audio_path.name}: {e}")
        return ""

def clean_transcript(raw_text: str) -> str:
    # Basic cleaning: remove repeated "OK", "uh", etc.
    import re
    text = raw_text.strip()
    text = re.sub(r"\b(uh|um|ok|okay|like)\b", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\s{2,}", " ", text)
    return text

def save_markdown(case_id: str, transcript: str, soap: dict, output_dir: Path):
    report_path = output_dir / f"{case_id}_report.md"
    with report_path.open("w") as f:
        f.write(f"# Case Report: {case_id}\n\n")
        f.write("## Summary\n\n")
        f.write(f"(Summary generated by LLM from transcript)\n\n")
        f.write("## SOAP Note\n\n")
        for section in ["subjective", "objective", "assessment", "plan"]:
            f.write(f"### {section.capitalize()}\n")
            f.write(soap.get(section, "") + "\n\n")
    print(f"[SAVED] Markdown report: {report_path}")

def main():
    parser = argparse.ArgumentParser(description="Audio to SOAP pipeline")
    parser.add_argument("--audio", required=True, help="Path to audio file or folder")
    parser.add_argument("--output-dir", required=True, help="Directory to save output")
    args = parser.parse_args()

    audio_input = Path(args.audio)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    audio_files = []

    if audio_input.is_dir():
        audio_files = list(audio_input.glob("*.wav")) + list(audio_input.glob("*.mp3"))
    elif audio_input.is_file():
        audio_files = [audio_input]
    else:
        print("[ERROR] Invalid audio path")
        sys.exit(1)

    if not audio_files:
        print("[ERROR] No audio files found.")
        sys.exit(1)

    for file in audio_files:
        case_id = file.stem
        transcript = transcribe_audio(file)
        if not transcript:
            continue

        cleaned = clean_transcript(transcript)

        # Save raw transcript
        (output_dir / f"{case_id}_transcript.txt").write_text(transcript)

        try:
            soap = call_soap_llm(cleaned, case_id)
        except Exception as e:
            print(f"[ERROR] LLM call failed: {e}")
            continue

        # Save JSON SOAP
        json_path = output_dir / f"{case_id}_soap.json"
        import json
        with json_path.open("w") as f:
            json.dump(soap, f, indent=2)
        print(f"[SAVED] SOAP JSON: {json_path}")

        # Save Markdown summary
        save_markdown(case_id, transcript, soap, output_dir)

if __name__ == "__main__":
    main()
